version: '3.9'

services:
  auth-service:
    build: ./authService
    ports:
      -"8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - IN_DOCKER=${IN_DOCKER}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - MY_GOOGLE_CLIENT_ID=${MY_GOOGLE_CLIENT_ID}
      - MY_GOOGLE_CLIENT_SECRET=${MY_GOOGLE_CLIENT_SECRET}
      - MY_GITHUB_CLIENT_SECRET=${MY_GITHUB_CLIENT_SECRET}
  user-service:
    build: ./userService
    ports:
      -"8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - IN_DOCKER=${IN_DOCKER}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    